### ISSUE TITLE
Hello I am new in roundcube development. I have round cube issue related spam filter. when i click on the spam filter in setting menu then it shows blank white page. what should i do?  

### ISSUE THREAD

**Issue by mgsf08m002** [6ec123321/filters#11]
in roundcube i have plugins folder where spam level plugin having 3 files namely spamlevel.css, spamlevel.js, spamlevel.php as i point on spam filter on the browser it pointed to the said folder in the URL as parameter. (Note it is the front end spam filter)

**Comment by bluexpres** [comment]
Hello,
Download latest filters files and upload them to plugins/filters directory. Then reopen roundcube with login. It fixes your issue.Do full backup your roundcube directory and database first.
