### ISSUE TITLE
Compatibility issue with Roundcube 1.2.0

### ISSUE THREAD

**Issue by nodo50** [6ec123321/filters#12]
Hi, I detected a issue with roundcube 1.2.0 and filters 2.1.4. The log show this error:

PHP Fatal error:  Call to undefined method rcube_imap::get_mailbox_name() in /var/www/roundcubemail/plugins/filters/filters.php on line 62

And the effect, when a user login, is a error 500 and the messages in inbox become inaccesible.

Thanks in advance

**Comment by rugebiker** [comment]
I also have this problem after upgrading to 1.2.0

**Comment by 6ec123321** [comment]
Try this https://github.com/6ec123321/filters/tree/filters_PHP7_RC1.2

**Comment by nodo50** [comment]
Hi 6ec123321, thanks, the patch works fine.
