### ISSUE TITLE
imap_connect()

### ISSUE THREAD

**Issue by syncgw** [6ec123321/filters#13]
Version 2.1.4

[24-Jul-2016 15:04:37 +0200]: <1ckf3ejb> Warning: Call to deprecated function Q(); See bc.inc for replacement
[24-Jul-2016 15:04:40 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined method rcmail::imap_connect() in plugins\filters\filters.php:193
Stack trace:
#0 program\include\rcmail_output_html.php(1127): filters->filters_form(Array)
#1 [internal function]: rcmail_output_html->xml_command(Array)
#2 program\include\rcmail_output_html.php(1004): preg_replace_callback('/<roundcube:([-...', Array, '<roundcube:obje...')
#3 program\include\rcmail_output_html.php(619): rcmail_output_html->parse_xml('<roundcube:obje...')
#4 program\include\rcmail_output_html.php(478): rcmail_output_html->parse('plugin', false)
#5 plugins\filters\filters.php(117): rcmail_output_html->send('plugin')
#6 program\lib\Roundcube\rcube_plugin_api.php(491): filters->filters_init()
#7 index.php(277): rcube_plugin_api->exec_action('plugin.filters')
#8 {main}
  thrown in plugins\filters\filters.php on line 193

**Comment by cewi** [comment]
seems we've a similar issue:
PHP Fatal error:  Call to undefined method rcube_imap::get_mailbox_name() in /var/www/roundcube/plugins/filters/filters.php on line 62
php is 5.6 and definitely has imap support:
dpkg -l | grep php5-imap:
ii  php5-imap                             5.6.24+dfsg-0+deb8u1              amd64        IMAP module for php5

**Comment by 6ec123321** [comment]
I think, need add the verify of version of PHP.


>Среда,  3 августа 2016, 22:06 +04:00 от cewi <notifications@github.com>:
>
>seems we've a similar issue:
>PHP Fatal error:  Call to undefined method rcube_imap::get_mailbox_name() in /var/www/roundcube/plugins/filters/filters.php on line 62
>php is 5.6 and definitely has imap support:
>dpkg -l | grep php5-imap:
>ii  php5-imap                             5.6.24+dfsg-0+deb8u1              amd64        IMAP module for php5
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
С уважением,
Инспекция гостехнадзора Удмуртской Республики,
Ведущий специалист-эксперт
Петров Артур Олегович
Факс/тел.: 8 (3412) 78-30-66
E-mail: gtnudm@yandex.ru

**Comment by cewi** [comment]
php-version should be 5.6.24 as is the imap module. Will verify that this evening.
FYI: I updated roundcube to 1.2.1. This broke the plugin. Before rc was 1.1.1 and worked with an older version of the filters-plugin without problems. After the update rc stopped working ("internal server error"). After disabling the plugin, rc worked again. I then updated the filters-plugin too (via composer, plugin now is dev-master). But the problem remained.

**Comment by 6ec123321** [comment]
Try this^
https://github.com/6ec123321/filters/tree/filters_PHP7_RC1.2  


>Четверг,  4 августа 2016, 10:50 +04:00 от cewi <notifications@github.com>:
>
>php-version should be 5.6.24 as is the imap module. Will verify that this evening.
>FYI: I updated roundcube to 1.2.1. This broke the plugin. Before rc was 1.1.1 and worked with an older version of the filters-plugin without problems. After the update rc stopped working ("internal server error"). After disabling the plugin, rc worked again. I then updated the filters-plugin too (via composer, plugin now is dev-master). But the problem remained. 
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
С уважением,
Инспекция гостехнадзора Удмуртской Республики,
Ведущий специалист-эксперт
Петров Артур Олегович
Факс/тел.: 8 (3412) 78-30-66
E-mail: gtnudm@yandex.ru

**Comment by cewi** [comment]
Seems to work. Thank you!

**Comment by 6ec123321** [comment]
I want make the fix, when the verify version of round cube, i known how doing that, but i don't have the time.


>Четверг,  4 августа 2016, 22:24 +04:00 от cewi <notifications@github.com>:
>
>Seems to work. Thank you!
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
С уважением,
Инспекция гостехнадзора Удмуртской Республики,
Ведущий специалист-эксперт
Петров Артур Олегович
Факс/тел.: 8 (3412) 78-30-66
E-mail: gtnudm@yandex.ru

**Comment by 6ec123321** [comment]
Not for me, one man make it modification, thank's to him please


>Четверг,  4 августа 2016, 22:24 +04:00 от cewi <notifications@github.com>:
>
>Seems to work. Thank you!
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
С уважением,
Инспекция гостехнадзора Удмуртской Республики,
Ведущий специалист-эксперт
Петров Артур Олегович
Факс/тел.: 8 (3412) 78-30-66
E-mail: gtnudm@yandex.ru

**Comment by 6ec123321** [comment]
Give me time, don't give me money, i don't work for money, if i want, if my work need for all, i'l do it. I do not have the time. Author of the plugin take my code and programming the plugin, time time time.


>Четверг,  4 августа 2016, 22:24 +04:00 от cewi <notifications@github.com>:
>
>Seems to work. Thank you!
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
С уважением,
Инспекция гостехнадзора Удмуртской Республики,
Ведущий специалист-эксперт
Петров Артур Олегович
Факс/тел.: 8 (3412) 78-30-66
E-mail: gtnudm@yandex.ru

**Comment by 6ec123321** [comment]
I know, about for you first question, for you mistakes, if you do not mistakes in future, reed bugtruk with loging in roundcube



>Четверг,  4 августа 2016, 22:33 +04:00 от Петров Артур Олегович <admin@gtn18.ru>:
>
>I want make the fix, when the verify version of round cube, i known how doing that, but i don't have the time.
>
>
>>Четверг,  4 августа 2016, 22:24 +04:00 от cewi < notifications@github.com >:
>>
>>Seems to work. Thank you!
>>—
>>You are receiving this because you commented.
>>Reply to this email directly,  view it on GitHub , or  mute the thread .
>
>
>-- 
>С уважением,
>Инспекция гостехнадзора Удмуртской Республики,
>Ведущий специалист-эксперт
>Петров Артур Олегович
>Факс/тел.: 8 (3412) 78-30-66
>E-mail:  gtnudm@yandex.ru


-- 
С уважением,
Инспекция гостехнадзора Удмуртской Республики,
Ведущий специалист-эксперт
Петров Артур Олегович
Факс/тел.: 8 (3412) 78-30-66
E-mail: gtnudm@yandex.ru
