### ISSUE TITLE
using filter driver to set and remove filters, filter removal has a bug.

### ISSUE THREAD

**Issue by johnwayne4d** [6ec123321/filters#16]
primary request: i use a filter driver to set and remove filters, but there is a bug. the driver developer says they cannot help.
here is the filter driver code:
`<?php

/**
- Filter learn driver
- @version 2.0
- @author Maxime Barrast
  *
- Copyright (C) 2015 Maxime Barrast
  *
- This driver is part of the MarkASJunk2 plugin for Roundcube.
  *
- This program is free software: you can redistribute it and/or modify
- it under the terms of the GNU General Public License as published by
- the Free Software Foundation, either version 3 of the License, or
- (at your option) any later version.
  *
- This program is distributed in the hope that it will be useful,
- but WITHOUT ANY WARRANTY; without even the implied warranty of
- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
- GNU General Public License for more details.
  *
- You should have received a copy of the GNU General Public License
- along with Roundcube. If not, see http://www.gnu.org/licenses/.
  */

class markasjunk2_filter_learn
{
    public function spam($uids, $mbox)
    {
        $this->_do_filterlearn($uids, true);
    }

```
public function ham($uids, $mbox)
{
    $this->_do_filterforget($uids, false);
}

private function _do_filterlearn($uids, $spam)
{
    $rcmail = rcube::get_instance();
    $user = $rcmail->user;


    foreach ($uids as $uid) {
        $MESSAGE = new rcube_message($uid);
        $from = $MESSAGE->sender['mailto'];

        if ($from == "")
          $rcmail->output->command('display_message', 'email address not found '.$from, 'error');
        else{
          $new_arr['whatfilter'] = 'from';
          $new_arr['searchstring'] = htmlspecialchars(addslashes($from));
          $new_arr['destfolder'] = addslashes("Junk");
          $new_arr['messages'] = 'all';
          $new_arr['filterpriority'] = '';
          $new_arr['markread'] = 'markread';
          $arr_prefs = $user->get_prefs();
          $arr_prefs['filters'][] = $new_arr;
          if ($user->save_prefs($arr_prefs))
            $rcmail->output->command('display_message', 'Junk filter entry for '.$from.' created', 'confirmation');
            // $rcmail->output->command('display_message', 'System learned that emails from '.$from.' are SPAM', 'confirmation');
          else
            $rcmail->output->command('display_message', 'Junk filter did nothing', 'error');
            // $rcmail->output->command('display_message', 'System learned nothing', 'error');
        }


    }


}


private function _do_filterforget($uids, $spam)
{
    $rcmail = rcmail::get_instance();
    $rcmail->imap_connect();
    $user = $rcmail->user;
    $arr_prefs = $user->get_prefs();

    foreach ($uids as $uid) {
        $MESSAGE = new rcube_message($uid);
        $from = $MESSAGE->sender['mailto'];

          $found = false;
          foreach ($arr_prefs['filters'] as $key => $saved_filter){

                if (stripslashes($saved_filter['searchstring']) == $from && $saved_filter['destfolder']== 'Junk' ){
                  $found = true;
                  $arr_prefs2 = $user->get_prefs();
                  $arr_prefs2['filters'][$key] = '';
                  $arr_prefs2['filters'] = array_diff($arr_prefs2['filters'], array(''));
                 if ($user->save_prefs($arr_prefs2))
                    $rcmail->output->command('display_message', 'Junk filter entry for '.$from.' removed', 'confirmation');
                    // $rcmail->output->command('display_message', 'Spam filter entry  '.$key.' removed', 'confirmation');
                 else
                    $rcmail->output->command('display_message', 'Junk filter entry for '.$from.' NOT removed', 'error');
                    // $rcmail->output->command('display_message', 'Spam filter entry  '.$key.' NOT removed', 'error');
                }


            }


            if(!$found) {
                 $rcmail->output->command('display_message', 'Junk filter entry for '.$from.' didnt exist', 'confirmation');
                 // $rcmail->output->command('display_message', 'Spam filter for '.$from.' didnt exist', 'confirmation');
            }


    }

}
```

}

?>`

the problem is that even though the created filter is properly NOT case sensitive (`$config['caseInsensitiveSearch'] = TRUE;`), the removal of a filter is incorrectly operating AS being case sensitive.

secondary and tertiary requests: features: after opening settings, then filters: have the ability to manually create filters based on send domain instead of the full email address. also have some way to click to move rules up and down (fitting in with the "do not process further rules" option.

thanks in advance.

would like to note, am attempting use of your plugin 2.1.4 with rc 1.1.6 . i did try plugin 2.2, but it seems that that is for newer versions of rc.

**Comment by donkikhot** [comment]
same error too when I try to create filter
247     foreach ($arr_prefs['filters'] as $key => $saved_filter){

**Comment by 6ec123321** [comment]
Fixed.
Tested:
Ubuntu 16.04 LTS Server
PHP 5.6.33-3+ubuntu16.04.1+deb.sury.org+1
MYSQL 5.7.21-0ubuntu0.16.04.1 - (Ubuntu)
Apache 2.4 (Ubuntu)
Roundcube 1.0.12 - LTS Version
Roundcube 1.1.10 - LTS Version
Roundcube 1.2.7 - Complete
Roundcube 1.3.4 - Complete

[PHP Modules]
calendar
Core
ctype
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache

- Try to test for Yourself.
