### ISSUE TITLE
problems with roundcube 1.2.2

### ISSUE THREAD

**Issue by mmiat** [6ec123321/filters#17]
the folders don't open, in log I've this error:

> PHP Fatal error:  Call to undefined method rcube_imap::mailbox_exists() in /usr/www/users/webmail/plugins/filters/filters.php on line 74

**Comment by hannesbe** [comment]
Exactly the same problem here with Roundcube 1.2.2

**Comment by 6ec123321** [comment]
Fixed for Roundcube v1.2.2, backward compatibility is preserved. Test and Close.

**Comment by 6ec123321** [comment]
fixed


>Понедельник, 28 ноября 2016, 12:33 +04:00 от Hannes Van de Vel <notifications@github.com>:
>
>Exactly the same problem here with Roundcube 1.2.2
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
С уважением,
Инспекция гостехнадзора Удмуртской Республики,
Ведущий специалист-эксперт
Петров Артур Олегович
Факс/тел.: 8 (3412) 78-30-66
E-mail: gtnudm@yandex.ru

**Comment by soltysek** [comment]
Current HEAD worked for me ;)
