### ISSUE TITLE
zh_TW translation file totally broken

### ISSUE THREAD

**Issue by dapphp** [6ec123321/filters#19]
Got a report from users with their language set to Chinese that they could not access settings and other pages.  Turns out this [file](https://github.com/6ec123321/filters/commit/50ab218829638c733ea7184af7bbe5a2a40f9b5b#diff-8484c06353ef146516c1ad61db18553a) was the cause.

Just removing all the `\` characters fixed it - but would like this to be fixed for future releases.

Thanks and good work on the plugin!

**Comment by 6ec123321** [comment]
Fixed, file chaged, thanks!

**Comment by dapphp** [comment]
:+1: thank you!
