### ISSUE TITLE
installed today, does not work, php undefined function

### ISSUE THREAD

**Issue by hlfritz** [6ec123321/filters#2]
I installed this today via composer, and when I attempt to view the inbox I get a red warning label across the top of the window stating:

"Server Error! (Internal Server Error)"
and no messages show in the inbox.  I do see messages in the inbox with squirrelmail.

the rc error log contains:

"[26-Aug-2015 16:03:16 America/Los_Angeles] PHP Fatal error:  Call to undefined function imap_mime_header_decode() in /var/www/rc/plugins/filters/filters.php on line 180"

**Comment by 6ec123321** [comment]
You need to basically ensure that php is compiled with the --with-imap option to use this function "imap_mime_header_decode" in your php code. To verify, call the phpinfo() function and check the configuration of php on your server and make sure the "--with-imap" option is there. If not present , you need to recompile php and go for the manual option which will enable you to include imap support for your php.

**Comment by 6ec123321** [comment]
And ofcourse, you needed to enable the “imap” module in the PHP config.

**Comment by 6ec123321** [comment]
Without recompile PHP you need install php_imap.so module from source/ports like in *BSD or rpm/deb package.

**Comment by hlfritz** [comment]
works!  but I think the requirement should be listed at least in the readme so people know.  thx!

**Comment by 6ec123321** [comment]
Re: [filters] installed today, does not work, php undefined function (#2)


Thanks!

Added PHP requirements to README.txt
-- 





works! but I think the requirement should be listed at least in the readme so people know. thx!
