### ISSUE TITLE
undefined function get_input_value() 

### ISSUE THREAD

**Issue by tycriss** [6ec123321/filters#20]
Hello,
I installed RC 1.3 beta with filters plugin enabled and following error appears when I want to create a filter:
Fatal error: Call to undefined function get_input_value() in /plugins/filters/filters.php on line 143
in
/?_task=settings&_action=plugin.filters-save

Any ideas?
Best regards
Tobias

**Comment by Gr4ffy** [comment]
Try with the current version.

**Comment by 6ec123321** [comment]
Fixed.
Updated to version 2.1.7
Tested:
Ubuntu 16.04 LTS Server
PHP 5.6.33-3+ubuntu16.04.1+deb.sury.org+1
MYSQL 5.7.21-0ubuntu0.16.04.1 - (Ubuntu)
Apache 2.4 (Ubuntu)
Roundcube 1.0.12 - LTS Version
Roundcube 1.1.10 - LTS Version
Roundcube 1.2.7 - Complete
Roundcube 1.3.4 - Complete

[PHP Modules]
calendar
Core
ctype
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache
