### ISSUE TITLE
Get the error "The fields `Contains` must not be empty"... but the field isn't empty

### ISSUE THREAD

**Issue by derekisbusy** [6ec123321/filters#23]
Get the error "The fields `Contains` must not be empty"... but the field isn't empty when adding a filter.

**Comment by flickflack2104** [comment]
This error appears with new roundcubemail version (1.3) but not with 1.1

**Comment by Zukrain** [comment]
ersion 2.1.6

**Comment by apterus** [comment]
Me too:
roundcube v 1.3.0
plugin 2.1.6
php 5.6.30

**Comment by Annabelle75** [comment]
Same error, what's interesting is turning on all error reporting, displayed and logged, shows nothing from PHP...

**Comment by derekisbusy** [comment]
@flickflack2104 @Zukrain @apterus @Annabelle75 @sl45sms

I sent a pull request with the fix. You can cherry-pick the update for now using git...

```
git cherry-pick af420c900d521598f418ae5f440f9af68013385f
```

or copy the filters folder from https://github.com/derekisbusy/filters/archive/master.zip into the plugins directory.

**Comment by Annabelle75** [comment]
Awesome! *LOVE* your github name! Thanks for the speedy fix :-)

**Comment by Zukrain** [comment]
It's worked. Thanks a lot

**Comment by 6ec123321** [comment]
I think, need to create a new branch for rcube 1.3 version. I'm using rcube 1.0.

**Comment by sniperivan** [comment]
this really working.THANKS

>  https://github.com/derekisbusy/filters/archive/master.zip

**Comment by 6ec123321** [comment]
Merged.
Tested:
Ubuntu 16.04 LTS Server
PHP 5.6.33-3+ubuntu16.04.1+deb.sury.org+1
MYSQL 5.7.21-0ubuntu0.16.04.1 - (Ubuntu)
Apache 2.4 (Ubuntu)
Roundcube 1.0.12 - LTS Version
Roundcube 1.1.10 - LTS Version
Roundcube 1.2.7 - Complete
Roundcube 1.3.4 - Complete

[PHP Modules]
calendar
Core
ctype
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache
