### ISSUE TITLE
Use filters without login?

### ISSUE THREAD

**Issue by yoshi1001** [6ec123321/filters#27]
Do filters work without login to roundcube?

**Comment by 6ec123321** [comment]
NO (НЕТ)


>Среда,  7 июня 2017, 13:28 +04:00 от yoshi1001 <notifications@github.com>:
>
>Do filters work without login to roundcube?
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
С уважением,
Инспекция гостехнадзора Удмуртской Республики,
Главный специалист-эксперт
Петров Артур Олегович
Факс/тел.:  8 (3412) 78-30-66
E-mail: gtnudm@yandex.ru
