### ISSUE TITLE
Roundcube Webmail 1.3.1 

### ISSUE THREAD

**Issue by syncgw** [6ec123321/filters#30]
Please update constants in filters.php (without you cannot add any new filter):
`    $searchstring = trim(rcube_utils::get_input_value('_searchstring', rcube_utils::INPUT_POST, true));
    $destfolder = trim(rcube_utils::get_input_value('_folders', rcube_utils::INPUT_POST, true));
    $whatfilter = trim(rcube_utils::get_input_value('_whatfilter', rcube_utils::INPUT_POST, true));
    $messages = trim(rcube_utils::get_input_value('_messages', rcube_utils::INPUT_POST, true));
    $filterpriority = trim(rcube_utils::get_input_value('_checkbox', rcube_utils::INPUT_POST, true));
	$markread = trim(rcube_utils::get_input_value('_markread', rcube_utils::INPUT_POST, true));
`

**Comment by 6ec123321** [comment]
Fixed.
Tested:
Ubuntu 16.04 LTS Server
PHP 5.6.33-3+ubuntu16.04.1+deb.sury.org+1
MYSQL 5.7.21-0ubuntu0.16.04.1 - (Ubuntu)
Apache 2.4 (Ubuntu)
Roundcube 1.0.12 - LTS Version
Roundcube 1.1.10 - LTS Version
Roundcube 1.2.7 - Complete
Roundcube 1.3.4 - Complete

[PHP Modules]
calendar
Core
ctype
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache
