### ISSUE TITLE
PHP Warning: php on line 247

### ISSUE THREAD

**Issue by donkikhot** [6ec123321/filters#31]
PHP 7.0.22-0ubuntu0.16.04.1
Roundcube Webmail 1.3.3
filters 2.1.6

_Hello i can not create filter 
I take this message_ 

[29-Nov-2017 13:53:47 Europe/Moscow] PHP Warning:  Invalid argument supplied for foreach() in /sites/www/roundcube/plugins/filters/filters.php on line 247

**Comment by 6ec123321** [comment]
Merged.
Tested:
Ubuntu 16.04  LTS Server
PHP 5.6.33-3+ubuntu16.04.1+deb.sury.org+1
MYSQL 5.7.21-0ubuntu0.16.04.1 - (Ubuntu) 
Apache 2.4 (Ubuntu)
Roundcube 1.0.12 - LTS Version
Roundcube 1.1.10 - LTS Version
Roundcube 1.2.7 - Complete
Roundcube 1.3.4 - Complete
