### ISSUE TITLE
Empty inbox "Loading..." stuck

### ISSUE THREAD

**Issue by ljoets** [6ec123321/filters#35]
Hi,
I installed filters plugin (dev-filters-2.1.7 with composer) on a fresh 1.3.6 RC.
When the plugin is activated, the mailbox doesn't shows mails, and I can see in the righ bottom corner a "Loading..." message.
When I disable the plugin in config.inc.php fil, mails are shown perfectly.

**Comment by 6ec123321** [comment]
show me your logfile in logs/errors

**Comment by ljoets** [comment]
I'm so sorry, the problem is solved while I try to reinstall the plugin. I can't explain this :-\
Here is what i did:

- drop all tables in database
- reinitialise database
- added "roundcube/filters": `"dev-filters-2.1.7"` in `composer.json` file and update `composer`.
- Log in -> everything works oO

Sorry ;-)

**Comment by 6ec123321** [comment]
Closed.

**Comment by 6ec123321** [comment]
Try this:
https://hub.docker.com/r/rcmail/rcmail/
