### ISSUE TITLE
Behavior of moving message to other folder

### ISSUE THREAD

**Issue by motomotomotto** [6ec123321/filters#37]
Hello , dear

I installed filters plugin on a  1.3.6 RC.
Now,  I confirmed issues of following on my develope env.

1) make folder that  includeing "#" character, not first letter.
      ※example「qwe#rty」
2) make filter rule that move the massage to "1)'s rule filter.
      ※example「Filter:subject  Contains:test  Move to:qwe#rty ~」       
3) send mail matching 2)'s rule and click "inbox".
4) the mailbox doesn't shows mails, and I see in the right bottom corner a "Loading..." message.

+ α
 ①chrome's dev tool, repeating "Get request" and finished on Status Code: 200

 ② I can move message to 1)'s filters by manual. 
     So that I think Roundcube's function "move_message" in "rcube_imap.php" is working correctlly.

Sorry, Please tell me your knowledge.
(Perhaps, RFC illigal?)

**Comment by 6ec123321** [comment]
This bug was fixed in roundcubemail 1.3.7 xD).

**Comment by 6ec123321** [comment]
You can fix this by your hands in this file:
https://github.com/6ec123321/docker-alpine-roundcubemail-1.3.6/commit/bd855786507ba7524bc6f00a3acee74ca5532fe7#diff-d1a082fbd8cdcc670e500ec859d13712

**Comment by 6ec123321** [comment]
Or, of you have stable 1.3.6 using this:
https://github.com/6ec123321/docker-alpine-roundcubemail-1.3.6

I using this in production.

**Comment by motomotomotto** [comment]
Dear,　6ec123321

Thank you very much！

I bothered you with my lack of catchup skills. ：＿（
I'll do my best.

bye.
