### ISSUE TITLE
search in headers for new filter rule

### ISSUE THREAD

**Issue by gerarcm** [6ec123321/filters#39]
This is a suggestion, rather than a bug report.
Can the filters plugin search headers? Say, for example, on a spamassassin tagged email -- if x-spam-status is true move to Spam, if spam score > 7 delete.

Thanks.

<<edit ... fixed a typo... sorry, and thanks. >>

**Comment by 6ec123321** [comment]
There's no such thing. Need to create one.

**Comment by 6ec123321** [comment]
Hello. Now i have many time to do this. Question about X-headers, there are many diffrent header for diffrent mail-servers. What do you think about diffrent headers ?

**Comment by 6ec123321** [comment]
Nothing. It's imposible yet. Read this https://github.com/roundcube/roundcubemail/issues/773.

**Comment by 6ec123321** [comment]
I will try xD), I need more information about the roundcube API. Learning strorage_init hook and other functions.

**Comment by 6ec123321** [comment]
Great, I have done it, Please, test.

**Comment by 6ec123321** [comment]
Great, I have done it, Please, test.

**Comment by 6ec123321** [comment]
Now, creat only check additional headers, but not "if spam score > 7 delete". Thinking about alghoritm for spam score.

**Comment by 6ec123321** [comment]
If you have production mal-server with amavisd+spamassasin+[antivirus], please, write in this Issue examples with non-spam and spam headers of mail messages, need for devel.

**Comment by gerarcm** [comment]
Hello.

no AV built in yet. but spamassassin headers follow:

Caught as HAM:
X-Spam-Status: No, score=-2.5 required=4.0 tests=ALL_TRUSTED,BAYES_00
        autolearn=ham autolearn_force=no version=3.4.2
X-Spam-Checker-Version: SpamAssassin 3.4.2 (2018-09-13) on
       local.host.domain

caught as SPAM:
X-Spam-Flag: YES
X-Spam-Status: Yes, score=4.0 required=4.0 tests=BAYES_99,BAYES_999,
        HTML_MESSAGE autolearn=no autolearn_force=no version=3.4.2
X-Spam-Level: ****
X-Spam-Checker-Version: SpamAssassin 3.4.2 (2018-09-13) on
        local.host.domain

X-Spam-Level --- the number of stars reflect on the score. we have a score of 4.0 as our determinant to select ham or spam. but a score over 7.0 is definitely no questions asked spam. Anything higher than 7 we can safely delete inmediately. Anything below that we want to keep (in Spam folder) so users can review for false positives.

Thanks.

**Comment by 6ec123321** [comment]
```
X-Spam-Status: Yes, score=4.0
```
is equivalent to 
```
X-Spam-Level: ****
```
?

**Comment by gerarcm** [comment]
Correct. The number of stars in X-Spam-Level equal the integer portion of the score. So, in my example, a score of 7.5 would yield an 
X-Spam-Level: *******

**Comment by 6ec123321** [comment]
Thx you to.

**Comment by 6ec123321** [comment]
Can set X-Spam-Status: Yes rule, but need score rule, if don't have accsess to mail server settings. Hmmm. I now how do it, but it's not beautiful - dirty programming. Need to take a break and think.

**Comment by 6ec123321** [comment]
Hmm, I can make another plugin specifically for antispam, what do you think about it?

**Comment by gerarcm** [comment]
Thank you.
