### ISSUE TITLE
Default filter

### ISSUE THREAD

**Issue by Birger52** [6ec123321/filters#4]
Defaulter is 
Where Subject contains **_SPAM**_ move it to spam folder.
and you can delete that filter as many times as needed - next time you open filters or they are activated, that filter is backagain.
How does one remove it, all the way?

**Comment by 6ec123321** [comment]
Re: [filters] Default filter (#4)


Здравствуйте, Birger52.

Вы писали 12 декабря 2015 г., 22:09:26:





Defaulter is 
Where Subject contains SPAM move it to spam folder
and you can delete that filter as many times as needed - next time you open filters or they are activated, that filter is backagain
How does one remove it, all the way?
—
Reply to this email directly or view it on GitHub.





What are your system settings

-- 
С уважением,
 Петров                          mailto:admin@gtn18.ru

**Comment by Birger52** [comment]
Win7
Apache 2.4.9 (wamp 2.5)
PHP 5.5.12
MySQL 5.6.17
Roundcube Webmail 1.2-git

**Comment by romjean** [comment]
You should switch the "$this->autoAddSpamFilterRule" to "FALSE" in the filters.php file.

RomJean

**Comment by Birger52** [comment]
Thx.
Seems to be functioning.
It's not in filters.php tho, rather in config.inc.php.dist

**Comment by 6ec123321** [comment]
Move settings from "filters.php" to "config.inc.php"

**Comment by Birger52** [comment]
Figured that one out...
Would be nice with an option to check all headers for a given string (eg. domain name), and an option to simply discard emails - not just move them to trash...
Emptying trash manually for now - works OK

**Comment by 6ec123321** [comment]
if i have more time, try do it

**Comment by Joykiller** [comment]
Hmmm. I get a 500 error in my inbox when a filter matches an email.

**Comment by 6ec123321** [comment]
We need to make one branch of plug-in work on all version of roundcube and PHP.

**Comment by 6ec123321** [comment]
Birger52, you say:
"Figured that one out...
Would be nice with an option to check all headers for a given string (eg. domain name), and an option to simply discard emails - not just move them to trash...
Emptying trash manually for now - works OK"

Great. Describe the logic of the whole process, so we don't think through what exactly it meant

**Comment by 6ec123321** [comment]
Birger52, you system is:
Win7
Apache 2.4.9 (wamp 2.5)
PHP 5.5.12
MySQL 5.6.17
Roundcube Webmail 1.2-git

Tell me please what software you are using, or what kind of distrib (Ubuntu, CetnOS), I needed a base for testing. No matter is Unix or Windows or Linux. Speed is very important in development.

**Comment by 6ec123321** [comment]
I studied to be a programmer. I sometimes wonder at times. My hobby is the system administrator. From the beginning, had for themselves the programming environment to configure, and then programming.

**Comment by 6ec123321** [comment]
Any there is No difference in Unix or Windows or Linux for programming nowadays. I know how to use all the strengths of each operating system. This is important

**Comment by 6ec123321** [comment]
I wanted to fix bugs in the plug-in filters, as a result of all I rewrote the algorithm, like Google or Yandex

**Comment by Birger52** [comment]
Hi Artur.

Been a while since I posted.
I'm not sure what you are asking, but I'll elaborate...

I have a Win7 PC running the wamp 2.5.
On that server, I also have hMailserver (https://www.hmailserver.com/) to read my mail.

In hMailserver, is an option for spam-filtering; filters from spamcop, spamhaus etc, and hMailserver also have SpamAssasin connected.
So somewhere around 95% of all spam are marked "*** SPAM ***" in the subject.
Also - reading them with Roundcube, does not display the original email, but the reason it was marked. And as these cannot be submitted to spamcop, there is no need to waste neother time nor space on them.
So I basically want an option, that simple deletes those emails without asking.
I do that manually (Shift and the delete ikon in Roundcube).
Also would be nice to have the option when designing specific filters, to delete emails from a given adress or a given domain.
And with delete, I don't mean move them to garbage, but delete them altogether.

My Roundcube is set to empty Trash when closed - it just doesn't do it. So all these unwanted emails, end up wasting space...

Hope this clearifies....
;)

**Comment by 6ec123321** [comment]
Fixed for Roundcube 1.2.2, thanks for Birger52. Close this or test on php-7.

**Comment by Birger52** [comment]
Thx - seems to be functioning.
