### ISSUE TITLE
Roundcube 1.3.6, no filter tab added

### ISSUE THREAD

**Issue by jimbowarrior** [6ec123321/filters#44]
Hello,

I use Ispconfig 3.1, ubuntu 18.04, nginx and Roundcube 1.3.6.
Plugin password works for example.
If I add "filters" 

$config['plugins'] = array(
 'password',
 'filters',
);

unfortunately, there is no filter tab into settings :-( 
How can I troubleshoot ?

 regards

**Comment by 6ec123321** [comment]
Installation
To install the plugin you have to:

Download zip-archive to Roundcube/plugins folder;
Unzip downloaded zip-archive;
Rename unziped folder to 'filters';

You do it ?

**Comment by jimbowarrior** [comment]
:/etc/letsencrypt/live# cd /etc/roundcube/plugins/filters/
:/etc/roundcube/plugins/filters# ls
README.md  composer.json  config.inc.php  filters.js  filters.php  localization  package.xml

**Comment by 6ec123321** [comment]
see /etc/roundcube/logs/errors

**Comment by jimbowarrior** [comment]
there is no error into  /var/log/mail.err regarding roundcube

**Comment by 6ec123321** [comment]
write to config.inc.php
```config['enable_installer'] = true;```

Open
```
http(s)://example.com/installer
```
Check settings and requerements of roundcube again

**Comment by jimbowarrior** [comment]
Checking PHP version
Version:  OK(PHP 7.2.15-1+ubuntu18.04.1+deb.sury.org+1 detected)
Checking PHP extensions

The following modules/extensions are required to run Roundcube:
PCRE:  OK
DOM:  OK
Session:  OK
XML:  OK
JSON:  OK
PDO:  OK
Multibyte:  OK
OpenSSL:  OK

The next couple of extensions are optional and recommended to get the best performance:
FileInfo:  OK
Libiconv:  OK
Intl:  OK
Exif:  OK
LDAP:  NOT AVAILABLE(See http://www.php.net/manual/en/book.ldap.php)
GD:  OK
Imagick:  OK
Checking available databases

Check which of the supported extensions are installed. At least one of them is required.
MySQL:  OK
PostgreSQL:  NOT AVAILABLE(See http://www.php.net/manual/en/ref.pdo-pgsql.php)
SQLite:  OK
SQLite (v2):  NOT AVAILABLE(See http://www.php.net/manual/en/ref.pdo-sqlite.php)
SQL Server (SQLSRV):  NOT AVAILABLE(See http://www.php.net/manual/en/ref.pdo-sqlsrv.php)
SQL Server (DBLIB):  NOT AVAILABLE(See http://www.php.net/manual/en/ref.pdo-dblib.php)
Oracle:  NOT AVAILABLE(See http://www.php.net/manual/en/book.oci8.php)
Check for required 3rd party libs

This also checks if the include path is set correctly.
PEAR:  OK
Auth_SASL:  OK
Net_SMTP:  OK
Net_IDNA2:  OK
Mail_mime:  OK
Net_LDAP3:  NOT AVAILABLE(Recommended to install Net_LDAP3 from git.kolab.org; See https://git.kolab.org/diffusion/PNL)
Checking php.ini/.htaccess settings

The following settings are required to run Roundcube:
file_uploads:  OK
session.auto_start:  OK
mbstring.func_overload:  OK
suhosin.session.encrypt:  OK

The following settings are optional and recommended:
allow_url_fopen:  OK
date.timezone:  OK


all seems ok

**Comment by 6ec123321** [comment]
check PHP errors in /var/log/

**Comment by 6ec123321** [comment]
Can you see version of filters-plugin in roundcube > about ?

**Comment by jimbowarrior** [comment]
no, only 

emoticons | 2.0 | GPLv3+ |  
-- | -- | -- | --
filesystem_attachments | 1.0 | GPLv3+ |  
jqueryui | 1.12.0 | GPLv3+ |  
password | 4.2

**Comment by jimbowarrior** [comment]
no log error into php

**Comment by 6ec123321** [comment]
I see, not Installed. Try install from https://plugins.roundcube.net/packages/roundcube/filters#dev-master with Composer

**Comment by 6ec123321** [comment]
Most likely, in the wrong place you edit the settings

**Comment by 6ec123321** [comment]
Roundcube can't seen the plugins that installed manuly. Download any plugin or try to rename folder password to password.bak and check roundcube>about menu.

**Comment by 6ec123321** [comment]
Or using this with docker.io
```
https://cloud.docker.com/u/ekonprof18/repository/docker/ekonprof18/rcmail
```

**Comment by jimbowarrior** [comment]
Problem 1
    - The requested package roundcube/filters ~2.1.9 exists as roundcube/filters[dev-filters-2.1.7, dev-filters-2.1.9, dev-master] but these are rejected by your constraint.

**Comment by 6ec123321** [comment]
Unable to find a Roundcube installation in /etc/roundcube - and what you think ?
The server is not configured properly. The problem is not in the plugin, the problem with setting up the server.

**Comment by jimbowarrior** [comment]
install with default ubuntu package and roundcube is installed into /etc/roundcube

**Comment by 6ec123321** [comment]
[Exception]
Unable to find a Roundcube installation in /etc/roundcube.
Try download source code from https://github.com/roundcube/roundcubemail/releases/download/1.3.8/roundcubemail-1.3.8-complete.tar.gz and install manualy.

**Comment by 6ec123321** [comment]
#!/bin/bash
cd /usr/share/roundcube/plugins
wget https://github.com/6ec123321/filters/archive/master.zip
unzip master.zip && mv filters-master filters
mkdir /etc/roundcube/plugins/filters && cd filters
mv config.inc.php /etc/roundcube/plugins/filters/config.inc.php
ln -s /etc/roundcube/plugins/filters/config.inc.php config.inc.php
ln -s /usr/share/roundcube/plugins/filters /var/lib/roundcube/plugins/filters

**Comment by jimbowarrior** [comment]
Thanks you very much !!!
