### ISSUE TITLE
Folder name with single quotation marks not filter

### ISSUE THREAD

**Issue by dudumacc** [6ec123321/filters#47]
Hi,

My user is trying to use a filter for a folder named MM's, but the filter does not work.
In database the filter points for the folder like "MM\\'s", i think that would be the motive of not doing the filter.

Can you help me with the solution to this case?

Thanks, Regards!

**Comment by 6ec123321** [comment]
Try new release https://github.com/6ec123321/filters/releases/tag/filters-2.2.0.
