### ISSUE TITLE
Internal Server Error when using specific filter

### ISSUE THREAD

**Issue by twisterbr** [6ec123321/filters#5]
If I configure a new rule to move specific messages to the same folder it's in, when I try to access that folder, I get Internal Server Error on roundcube page, and on logs/errors I get this:
[05-Jan-2016 10:51:06 America/Sao_Paulo] PHP Fatal error:  Call to undefined function imap_mime_header_decode() in /var/www/xxxxxxxx/plugins/filters/filters.php on line 180

I think there should be a specific check before applying the rule that sees if the message is already on the folder the rule is configured to move to.

Sorry for my bad english..

**Comment by romjean** [comment]
I have this issue too. I guess we need to re-install php compiling with the imap-module, isn't it 6ec123321 ?

**Comment by twisterbr** [comment]
Wtf! How stupid am I? I read the error log but did not payed attention to it: I had no php5-imap module installed on my server. After I installed and loaded the module the error was gone.

Sorry guys for my noobiness and for taking your time.
