### ISSUE TITLE
the template broke up in RC 1.4

### ISSUE THREAD

**Issue by marasaka** [6ec123321/filters#51]
Hi, In RC1.4 the template become to be "too big".
You heve to reduce the screen to 80% to be able to see existed filters rules.
Many users will not discover this.

Best regards

**Comment by nicolas-joubert** [comment]
Hello marasaka,
i've made a quick & ugly patch for this here : https://github.com/nicolas-joubert/filters/commit/3c7d46ab603a19b77d10fe8ddc033053023df7e9

Best regards

**Comment by 6ec123321** [comment]
> i've made a quick & ugly patch for this here : [nicolas-joubert@3c7d46a](https://github.com/nicolas-joubert/filters/commit/3c7d46ab603a19b77d10fe8ddc033053023df7e9)

Hello all.
If this patch working, please, create pull request.

**Comment by 6ec123321** [comment]
Update to version 2.2.1.
https://github.com/6ec123321/filters/releases/tag/filters-2.2.1
