### ISSUE TITLE
I have no idea how to configure these

### ISSUE THREAD

**Issue by f1-outsourcing** [6ec123321/filters#52]
How should I configure these

```
//$config['autoAddSpamFilterRule'] = TRUE;
//$config['spam_subject'] = '[SPAM]';
//$config['caseInsensitiveSearch'] = TRUE;
//$config['decodeBase64Msg'] = FALSE;
//$config['spam_headers'] = array('X-Spam-Flag','X-Spam-Status','X-Yandex-Spam');
```

If my messages are arriving with 
X-Spam-Flag: YES
and having a subject that starts with 
*****SPAM*****

So that these messages are automatically moved to the spam folder (with creating a new account)?

**Comment by 6ec123321** [comment]
$config['autoAddSpamFilterRule'] = true;
$config['spam_subject'] = 'SPAM';
$config['caseInsensitiveSearch'] = false;
$config['decodeBase64Msg'] = FALSE;
$config['spam_headers'] = array('X-Spam-Flag','X-Spam-Status','X-Yandex-Spam');

**Comment by 6ec123321** [comment]
> So that these messages are automatically moved to the spam folder (with creating a new account)?
Yes, if you installed rc version >=1.3.9.

**Comment by f1-outsourcing** [comment]
But I thought docs say $config['spam_subject'] = 'SPAM'; changes the subject? My messages are already scanned, I do not want this plugin to alter anything, just move it into a folder. And where do I configure then the folder name?

**Comment by f1-outsourcing** [comment]
Maybe tip: if you delete the filter, put it back in the form fields, that would make it easier for people to edit.

**Comment by 6ec123321** [comment]
> But I thought docs say $config['spam_subject'] = 'SPAM'; changes the subject? My messages are already scanned, I do not want this plugin to alter anything, just move it into a folder. And where do I configure then the folder name?

If all working of you want, do not edit enithing in config.inc.php. All settings saved in "users" table of rc database.

If
$config['autoAddSpamFilterRule'] = true;
then rules automatical add two rules:
1. Scan message in field subject like SPAME ($config['spam_subject'] = 'SPAM';)
2. Scan message in field X-Spam-Flag (search string "X-Spam-Flag: YES").

You can edit filters.php function filters_addMoveSpamRule in the end of the file and add/edit auto-add spam filter rules.

Plugin filters is a open-source simple client-side sorting for user-mail messages. Do it what you want with this.

**Comment by 6ec123321** [comment]
folder name you can configure in filters.php. If you want you can write pach for filters.php and config.inc.php for default rules.
