### ISSUE TITLE
IMAP errors

### ISSUE THREAD

**Issue by nightah** [6ec123321/filters#7]
Just installed and attempted to check my mailbox, as per issue #2 I'm receiving the same error:

An Error Occurred!
Server Error! (OK)

php version 7.0.4 compiled with imap support
Roundcube 1.2-beta3

Error logs state: 

```
[03-Mar-2016 10:27:54 Australia/Melbourne] PHP Fatal error:  Uncaught Error: Call to undefined method rcube_imap::get_mailbox_name() in /usr/share/webapps/roundcubemail/plugins/filters/filters.php:62
Stack trace:
#0 /usr/share/webapps/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php(439): filters->filters_checkmsg(Array)
#1 /usr/share/webapps/roundcubemail/program/steps/mail/func.inc(429): rcube_plugin_api->exec_hook('messages_list', Array)
#2 /usr/share/webapps/roundcubemail/program/steps/mail/list.inc(103): rcmail_js_message_list(NULL, false, Array)
#3 /usr/share/webapps/roundcubemail/index.php(291): include_once('/usr/share/weba...')
#4 {main}
  thrown in /usr/share/webapps/roundcubemail/plugins/filters/filters.php on line 62
```

phpinfo() output:

`Configure Command	'./configure' '--srcdir=../php-7.0.4' '--config-cache' '--prefix=/usr' '--sbindir=/usr/bin' '--sysconfdir=/etc/php' '--localstatedir=/var' '--with-layout=GNU' '--with-config-file-path=/etc/php' '--with-config-file-scan-dir=/etc/php/conf.d' '--disable-rpath' '--mandir=/usr/share/man' '--without-pear' '--enable-zend-signals' '--enable-cgi' '--enable-fpm' '--with-fpm-systemd' '--with-fpm-acl' '--with-fpm-user=http' '--with-fpm-group=http' '--enable-embed=shared' '--enable-bcmath=shared' '--enable-calendar=shared' '--enable-dba=shared' '--enable-exif=shared' '--enable-ftp=shared' '--enable-gd-native-ttf' '--enable-intl=shared' '--enable-mbstring' '--enable-shmop=shared' '--enable-soap=shared' '--enable-sockets=shared' '--enable-sysvmsg=shared' '--enable-sysvsem=shared' '--enable-sysvshm=shared' '--enable-zip=shared' '--with-bz2=shared' '--with-curl=shared' '--with-db4=/usr' '--with-enchant=shared,/usr' '--with-freetype-dir=/usr' '--with-gd=shared,/usr' '--with-gdbm' '--with-gettext=shared' '--with-gmp=shared' '--with-iconv=shared' '--with-imap-ssl' '--with-imap=shared' '--with-kerberos=/usr' '--with-ldap=shared' '--with-ldap-sasl' '--with-libzip' '--with-mcrypt=shared' '--with-mhash' '--with-mysql-sock=/run/mysqld/mysqld.sock' '--with-mysqli=shared,mysqlnd' '--with-openssl' '--with-pcre-regex=/usr' '--with-pdo-dblib=shared,/usr' '--with-pdo-mysql=shared,mysqlnd' '--with-pdo-odbc=shared,unixODBC,/usr' '--with-pdo-pgsql=shared' '--with-pdo-sqlite=shared,/usr' '--with-pgsql=shared' '--with-pspell=shared' '--with-readline' '--with-snmp=shared' '--with-sqlite3=shared,/usr' '--with-tidy=shared' '--with-unixODBC=shared,/usr' '--with-xmlrpc=shared' '--with-xsl=shared' '--with-zlib' '--enable-pcntl' 'CFLAGS=-march=x86-64 '-mtune=generic' '-O2' '-pipe' '-fstack-protector-strong'' 'LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CXXFLAGS=-march=x86-64 '-mtune=generic' '-O2' '-pipe' '-fstack-protector-strong''`

The extension imap.so has also been enabled in my php.ini.

Could this be due to the version of Roundcube that I'm running?

**Comment by alecpl** [comment]
Incompatibility with 1.2. Replace get_mailbox_name() with get_folder().

**Comment by alecpl** [comment]
And there will be more issues. See https://github.com/roundcube/roundcubemail/commit/454b0b1ca983adfa2e40e47ccbd0dc384c141d9a

**Comment by alecpl** [comment]
BTW, Roundcube does not use php-imap extension at all.

**Comment by nicolas-joubert** [comment]
@nightah @alecpl My fix is finish and working well.
